In [1]:
import pandas as pd

In [2]:
s = pd.Series([10,20,30], index=['a','b','c'])
print(s)

a    10
b    20
c    30
dtype: int64

In [4]:
s['a']

10

In [6]:
data = {'math' : 80, 'phys' : 90, 'chem' : 85}
s = pd.Series(data)
print(s)

math    80
phys    90
chem    85
dtype: int64

#Creating DataFrame from Dictionary

In [9]:
data = {
    'name' :['Alice', 'Bob', 'Charlie'],
    'age' : [24,30,22],
    'salary' : [50000,60000,55000]
}
df = pd.DataFrame(data)
print(df)

      name  age  salary
0    Alice   24   50000
1      Bob   30   60000
2  Charlie   22   55000

In [10]:
type(df['age'])

pandas.core.series.Series

Reading Data

In [11]:
df = pd.read_csv('data.csv')

In [12]:
pd.read_csv('data.csv',sep=',',header = 0 , encoding = 'utf-8')

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
#for Excel

pd.read_excel('data.xlsx')

In [ ]:
🔹 From Dictionary / List of Lists
pd.DataFrame([[1,2],[3,4]], columns=['A','B'])

In [15]:
df.head()

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [16]:
df.tail()

   Country   Age   Salary Purchased
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [17]:
df.head(10)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [18]:
df.shape

(10, 4)

In [19]:
df.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [22]:
df.dtypes

Country       object
Age          float64
Salary       float64
Purchased     object
dtype: object

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    10 non-null     object
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes

In [28]:
df['Age']

0    44.0
1    27.0
2    30.0
3    38.0
4    40.0
5    35.0
6     NaN
7    48.0
8    50.0
9    37.0
Name: Age, dtype: float64

In [32]:
df[['Country' , 'Salary']]

   Country   Salary
0   France  72000.0
1    Spain  48000.0
2  Germany  54000.0
3    Spain  61000.0
4  Germany      NaN
5   France  58000.0
6    Spain  52000.0
7   France  79000.0
8  Germany  83000.0
9   France  67000.0

In [46]:
df.loc[0:2]

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No

In [34]:
df.iloc[0]

Country       France
Age             44.0
Salary       72000.0
Purchased         No
Name: 0, dtype: object

9️⃣ Filtering Data (VERY IMPORTANT)

🔹 Simple Condition

In [51]:
df[df['Age'] > 25]

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

🔹 Multiple Conditions

In [53]:
df[(df['Age'] > 25) & (df['Salary' ] > 50000)]

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

🔟 Modifying Data

In [55]:
df['tax']=df['Salary'] *0.1

In [56]:
df['tax']

0    7200.0
1    4800.0
2    5400.0
3    6100.0
4       NaN
5    5800.0
6    5200.0
7    7900.0
8    8300.0
9    6700.0
Name: tax, dtype: float64

Update Values

In [58]:
df.loc[df['Age'] > 25, 'Salary'] += 5000

In [59]:
df['Age']

0    44.0
1    27.0
2    30.0
3    38.0
4    40.0
5    35.0
6     NaN
7    48.0
8    50.0
9    37.0
Name: Age, dtype: float64

In [60]:
df['Salary']

0    77000.0
1    53000.0
2    59000.0
3    66000.0
4        NaN
5    63000.0
6    52000.0
7    84000.0
8    88000.0
9    72000.0
Name: Salary, dtype: float64

In [62]:
df.rename(columns={'Salary': 'Income'}, inplace= True)

Rename Columns

In [64]:
df['Income']

0    77000.0
1    53000.0
2    59000.0
3    66000.0
4        NaN
5    63000.0
6    52000.0
7    84000.0
8    88000.0
9    72000.0
Name: Income, dtype: float64

🔹 Drop Column / Row

In [65]:
df.drop('tax' , axis=1, inplace = True)
df.drop(0, axis=0, inplace=True)

1️⃣1️⃣ Handling Missing Values (REAL DATA IS DIRTY)

In [68]:
df.isnull()

   Country    Age  Income  Purchased
1    False  False   False      False
2    False  False   False      False
3    False  False   False      False
4    False  False    True      False
5    False  False   False      False
6    False   True   False      False
7    False  False   False      False
8    False  False   False      False
9    False  False   False      False

In [69]:
df.isnull().sum()

Country      0
Age          1
Income       1
Purchased    0
dtype: int64

In [70]:
df.dropna()

   Country   Age   Income Purchased
1    Spain  27.0  53000.0       Yes
2  Germany  30.0  59000.0        No
3    Spain  38.0  66000.0        No
5   France  35.0  63000.0       Yes
7   France  48.0  84000.0       Yes
8  Germany  50.0  88000.0        No
9   France  37.0  72000.0       Yes

In [74]:
df.fillna(0)
df['Age'].fillna(df['Age'].mean())

1    27.000
2    30.000
3    38.000
4    40.000
5    35.000
6    38.125
7    48.000
8    50.000
9    37.000
Name: Age, dtype: float64

1️⃣2️⃣ Sorting Data

In [84]:
df.sort_values(by ='Income')

   Country   Age   Income Purchased
6    Spain   NaN  52000.0        No
1    Spain  27.0  53000.0       Yes
2  Germany  30.0  59000.0        No
5   France  35.0  63000.0       Yes
3    Spain  38.0  66000.0        No
9   France  37.0  72000.0       Yes
7   France  48.0  84000.0       Yes
8  Germany  50.0  88000.0        No
4  Germany  40.0      NaN       Yes

In [85]:
df.sort_values(by ='Income', ascending = False)

   Country   Age   Income Purchased
8  Germany  50.0  88000.0        No
7   France  48.0  84000.0       Yes
9   France  37.0  72000.0       Yes
3    Spain  38.0  66000.0        No
5   France  35.0  63000.0       Yes
2  Germany  30.0  59000.0        No
1    Spain  27.0  53000.0       Yes
6    Spain   NaN  52000.0        No
4  Germany  40.0      NaN       Yes

1️⃣3️⃣ GroupBy (MOST POWERFUL FEATURE)

Think:

“Split → Apply → Combine”

In [87]:
df.groupby('Country')['Income'].mean()

Country
France     73000.0
Germany    73500.0
Spain      57000.0
Name: Income, dtype: float64

In [91]:
df.groupby('Country').agg({'Income':['mean','max'],'Age':'mean'})

          Income            Age
            mean      max  mean
Country
France   73000.0  84000.0  40.0
Germany  73500.0  88000.0  40.0
Spain    57000.0  66000.0  32.5

1️⃣4️⃣ Applying Functions
🔹 Apply on Column

In [94]:
df['Income'] = df['Income'].apply(lambda x: x*1.1)

In [96]:
df['Income']

1    58300.0
2    64900.0
3    72600.0
4        NaN
5    69300.0
6    57200.0
7    92400.0
8    96800.0
9    79200.0
Name: Income, dtype: float64

🔹 Apply on Rows

In [2]:
df.apply(sum, axis=0)

NameError: name 'df' is not defined